import { emptyAnswers, emptyProvider, type FormAnswers } from "./types";

/** Healthy-ish GCC High enclave. */
export function sampleHealthy(): FormAnswers {
  return {
    ...emptyAnswers(),
    hqname: "Alder Holdings LLC",
    uei: "XK3MNB7P2Q14",
    oscname: "Alder Precision, Inc.",
    dba: "Alder Precision",
    address1: "410 Narragansett Ave",
    address2: "Suite 12",
    city: "Warwick",
    state: "RI",
    zip: "02888",
    country: "United States",
    businessphone: "401-555-0142",
    website: "https://alder.example",
    sector: "Defense Industrial Base",
    employees: "85",
    hlocage: "1H9QX",
    cageinscope: "1H9QX",
    scopemode: "Enclave",
    scopedesc: "GCC High plus locked-down CAD workstations. Commercial M365 is out.",
    ao_last: "Chen",
    ao_first: "Maya",
    ao_title: "Contracts manager / Affirming Official",
    ao_email: "maya.chen@alder.example",
    ao_phone: "401-555-0142",
    tpoc_last: "Ortiz",
    tpoc_first: "Luis",
    tpoc_title: "IT lead",
    tpoc_email: "luis.ortiz@alder.example",
    tpoc_phone: "401-555-0148",
    has_sps: "Yes",
    sps: [
      {
        ...emptyProvider(),
        name: "Northwind MSP",
        email: "sam.patel@northwindmsp.example",
        job: "MSP",
        cui_or_spd: "Security-protection data only",
        own_cmmc: "No",
        admin_access: "No",
        crm_inherited: "Yes",
        vendor_srm: "Yes",
      },
    ],
    employees_total: "85",
    cui_users: "22",
    interview_roles_namable: "Yes",
    interview_role_names: "IT lead, contracts manager, CAD supervisor",
    devices_workstations: "14 CAD workstations",
    devices_laptops: "8 GCC High laptops",
    devices_servers: "2 file servers in the enclave",
    devices_mobile: "None in CUI path",
    device_classes: ["Workstations", "Laptops", "Servers"],
    cui_locations: ["M365 GCC High", "On-prem file shares / servers"],
    cui_locations_note: "Drawings land in GCC High SharePoint and a on-prem file share inside the enclave.",
    cui_host_fedramp: [
      { host: "M365 GCC High", fedramp: "FedRAMP Authorized", offering_name: "Office 365 GCC High" },
      { host: "On-prem file shares / servers", fedramp: "N/A", offering_name: "" },
    ],
    cui_flow: "Prime emails a link into GCC High. Engineer opens CAD on an enclave workstation. As-built packet goes back through GCC High to the prime. No CUI on Commercial email.",
    cui_leaves_portable: "No",
    vdi_download_print: "N/A",
    cui_off_hq: "No",
    cui_backup_commercial: "No",
    cui_backup_where: "GCC High",
    physical_cui_observe: "No",
    virtual_tour_exposes_cui: "No",
    dlp_blocks_screenshare: "Yes",
    env_mode: "GCC High tenant",
    enclave_what: "",
    enclave_fedramp: "FedRAMP High (or equiv, e.g. GCC High)",
    boundary_defined: "Yes",
    network_diagram: "Yes",
    diagram_vs_matrix: "Yes",
    separation: "Both",
    count_cui_assets: "Some (11–50)",
    count_spa: "A few (1–10)",
    count_crma: "A few (1–10)",
    crma_enforce: "Technically enforced",
    has_crma: "Yes",
    crma_handles_cui: "No",
    specialized_kinds: ["OT", "Other"],
    count_specialized: "OT",
    specialized_notes: "CNC controllers, CMM — 8. CUI not stored on them; USB blocked.",
    count_oos: "Many (51+)",
    oos_can_reach_cui: "No",
    oos_justification: "No CUI accounts, no enclave routing, separate IdP.",
    contmon_tool: "CrowdStrike + Microsoft Sentinel (GCC High)",
    contmon_who: "Luis Ortiz + Northwind SOC",
    contmon_howoften: "Daily SOC; weekly OSC review",
    mfa_solution: "Entra ID MFA (number matching) + hardware keys for admin",
    mfa_coverage: "All remote and privileged",
    mfa_uncovered: "None known",
    esp_kinds: ["MSP", "CSP"],
    esp_who: "",
    esp_csp: "Yes",
    esp_fedramp: "FedRAMP High (or equiv, e.g. GCC High)",
    csp_needs_own_cmmc: "No",
    esp_crm: "Yes",
    vendor_srm_on_file: "Yes",
    esp_admin_access: "No",
    esp_crm_names_inherited: "Yes",
    ssp_exists: "Yes",
    ssp_updated: "2026-06-01",
    ssp_matches: "Yes",
    ssp_artifacts_exist: "Yes",
    ssp_artifact_types: "SSP, policies, procedures, diagrams, inventory",
    inventory_exists: "Yes",
    inventory_current: "Yes",
    poam_open: "No",
    poam_conditional: "N/A",
    poam_notes: "",
    evidence_share: "Box",
    fix_during_assessment: "No",
    freeze_during_assessment: "Yes",
    migrate_during_assessment: "No",
    consent_nocui: true,
    consent_notassessment: true,
  };
}

/**
 * Hidden tester OSC for `?demo=1`. Complete required set so Submit can succeed.
 * Harborline-style GCC High enclave — not shown on the public form.
 */
export function sampleHarborline(): FormAnswers {
  return {
    ...sampleHealthy(),
    hqname: "Harborline Precision LLC",
    oscname: "Harborline Precision",
    dba: "Harborline",
    uei: "HBR1LN0SC014",
    address1: "18 Thames St",
    city: "Newport",
    state: "RI",
    zip: "02840",
    businessphone: "401-555-0188",
    website: "https://harborline.example",
    hlocage: "8H2LP",
    cageinscope: "8H2LP",
    scopedesc: "GCC High plus on-prem file share. Corporate M365 Commercial is out.",
    ao_email: "maya.chen@harborline.example",
    ao_phone: "401-555-0188",
    tpoc_email: "luis.ortiz@harborline.example",
    tpoc_phone: "401-555-0189",
    cui_locations_note: "Drawings land in GCC High SharePoint and an on-prem file share inside the enclave.",
    cui_flow: "Prime emails a link into GCC High. Engineer opens CAD on an enclave workstation. As-built packet goes back through GCC High to the prime. No CUI on Commercial email.",
  };
}

/** Red-flag: no SSP, commercial M365, no MFA, no diagram. */
export function sampleMessy(): FormAnswers {
  return {
    ...emptyAnswers(),
    hqname: "Cedar Logistics Co.",
    uei: "J8Q2LM44N001",
    oscname: "Cedar Logistics Co.",
    dba: "",
    address1: "90 Doremus Ave",
    city: "Newark",
    state: "NJ",
    zip: "07105",
    country: "United States",
    businessphone: "973-555-0160",
    website: "https://cedarlogistics.example",
    sector: "Transportation Systems",
    employees: "40",
    hlocage: "4P0TT",
    cageinscope: "4P0TT",
    scopemode: "Enclave",
    scopedesc: "We thought the dispatch PCs were an enclave.",
    ao_last: "Rivera",
    ao_first: "Alex",
    ao_title: "Owner",
    ao_email: "alex.rivera@cedarlogistics.example",
    ao_phone: "973-555-0160",
    tpoc_last: "Rivera",
    tpoc_first: "Alex",
    tpoc_title: "IT lead",
    tpoc_email: "alex.rivera@cedarlogistics.example",
    tpoc_phone: "973-555-0160",
    has_sps: "Yes",
    sps: [
      {
        ...emptyProvider(),
        name: "Office365 / local break-fix shop",
        email: "chris@breakfix.example",
        job: "CSP",
        cui_or_spd: "Stores, processes, or transmits CUI",
        fedramp: "Not authorized",
        own_cmmc: "Don't know",
        admin_access: "Yes",
        crm_inherited: "No",
        vendor_srm: "No",
      },
    ],
    employees_total: "40",
    cui_users: "8",
    interview_roles_namable: "Don't know",
    devices_workstations: "6 dispatch PCs",
    devices_laptops: "8 personal laptops",
    devices_servers: "None",
    devices_mobile: "Phones on email",
    device_classes: ["Workstations", "Laptops", "Home / BYOD"],
    cui_locations: ["M365 Commercial", "Email (non-PreVeil)", "On-prem file shares / servers"],
    cui_locations_note: "Drawings and shipment files sit in the same commercial OneDrive as HR.",
    cui_host_fedramp: [
      { host: "M365 Commercial", fedramp: "Not authorized", offering_name: "" },
      { host: "Email (non-PreVeil)", fedramp: "Not authorized", offering_name: "" },
      { host: "On-prem file shares / servers", fedramp: "N/A", offering_name: "" },
    ],
    cui_flow: "Prime emails attachments to personal and company mail. Files copied to a shared drive. No CUI content pasted here.",
    cui_leaves_portable: "Yes",
    vdi_download_print: "Yes",
    cui_off_hq: "Yes",
    cui_off_hq_note: "Home laptops and warehouse PCs.",
    other_sites: "Newark warehouse; home offices",
    cui_backup_commercial: "Yes",
    cui_backup_where: "Commercial cloud",
    physical_cui_observe: "Yes",
    virtual_tour_exposes_cui: "Yes",
    dlp_blocks_screenshare: "No",
    env_mode: "Broader environment",
    enclave_what: "",
    enclave_fedramp: "No / not authorized",
    boundary_defined: "No",
    network_diagram: "No",
    diagram_vs_matrix: "No",
    separation: "Neither / unclear",
    count_cui_assets: "Don't know",
    count_spa: "Don't know",
    count_crma: "Don't know",
    crma_enforce: "Policy-only",
    has_crma: "Yes",
    crma_handles_cui: "Yes",
    specialized_kinds: ["None"],
    count_specialized: "None",
    count_oos: "Don't know",
    oos_can_reach_cui: "Yes",
    oos_justification: "Have not mapped out-of-scope assets; dispatch PCs, personal laptops, and the commercial tenant all mix.",
    contmon_tool: "None",
    contmon_who: "Nobody assigned",
    contmon_howoften: "Ad hoc",
    mfa_solution: "SMS on some mailboxes",
    mfa_coverage: "Not enforced",
    mfa_uncovered: "Owner and two dispatchers; vendor admin",
    esp_kinds: ["MSP", "Other"],
    esp_who: "Local break-fix shop",
    esp_csp: "Yes",
    esp_fedramp: "No / not authorized",
    csp_needs_own_cmmc: "Don't know",
    esp_crm: "No",
    vendor_srm_on_file: "No",
    esp_admin_access: "Yes",
    esp_crm_names_inherited: "No",
    ssp_exists: "No",
    ssp_updated: "",
    ssp_matches: "No",
    inventory_exists: "No",
    inventory_current: "No",
    poam_open: "Yes",
    poam_conditional: "No",
    poam_notes: "We planned to write the SSP during the C3PAO week.",
    evidence_share: "Box",
    fix_during_assessment: "Yes",
    freeze_during_assessment: "No",
    migrate_during_assessment: "Yes",
    consent_nocui: true,
    consent_notassessment: true,
  };
}
