# OWASP ZAP Automation Framework plan — Scoping Track B baseline.
# Generated by scripts/zap-baseline.sh. Spider + passive only. No active scan.
# Placeholders: __TARGET_ORIGIN__ __TARGET_URL__ __REPORT_DIR__ __SPIDER_MINS__ __LIGHT_JOBS__
---
env:
  contexts:
    - name: prescope-intake
      urls:
        - "__TARGET_ORIGIN__"
      includePaths:
        - "__TARGET_ORIGIN__/.*"
      excludePaths:
        - "__TARGET_ORIGIN__/api/assessor/emass.*"
        - "__TARGET_ORIGIN__/api/submissions.*"
        - "__TARGET_ORIGIN__/drop/.*/internal.*"
        - "__TARGET_ORIGIN__/api/submit.*"
        - "https://prescope-submit.example.workers.dev.*"
  parameters:
    failOnError: false
    failOnWarning: false
    progressToStdout: true
    continueOnFailure: true

jobs:
  - type: passiveScan-config
    parameters:
      enableTags: false
      maxAlertsPerRule: 10

  - type: spider
    parameters:
      context: prescope-intake
      url: "__TARGET_URL__"
      maxDuration: __SPIDER_MINS__
      maxDepth: 8
      maxChildren: 30
      threadCount: 2
      parseComments: true
      parseRobotsTxt: true
      parseSitemapXml: true
      postForm: false
      processForm: false
      userAgent: "ScopingAuthorizedDAST/1.0 (ZAP-Baseline; +https://github.com/GRCJP/Assessment-Scoping)"
    tests:
      - name: at least 1 URL found
        type: stats
        statistic: automation.spider.urls.added
        operator: ">="
        value: 1
        onFail: info

__LIGHT_JOBS__
  - type: passiveScan-wait
    parameters:
      maxDuration: 3

  - type: report
    parameters:
      template: traditional-html
      reportDir: "__REPORT_DIR__"
      reportFile: "zap-baseline-report"
      reportTitle: "Scoping Track B — ZAP Baseline (authorized)"
      reportDescription: "Spider + passive scan only. No active scan, no secret probing."

  - type: report
    parameters:
      template: traditional-json
      reportDir: "__REPORT_DIR__"
      reportFile: "zap-baseline-report"
      reportTitle: "Scoping Track B — ZAP Baseline (authorized)"
      reportDescription: "Spider + passive scan only. No active scan, no secret probing."
